data: 'data/save_data/'
logF: 'experiments/'
tensorboard: False
tensorboard_log_dir: 'experiments/opensub/tensorboard/s2s/'
epoch: 50
batch_size: 64
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
param_init: 0.04
param_init_glorot: False
learning_rate: 1
max_grad_norm: 1
learning_rate_decay: 0.95
start_decay_steps: 10000
warmup_steps: 4000
decay_method: "noam"
beta1: 0.9
beta2: 0.998
emb_size: 512
hidden_size: 512
dec_num_layers: 2
enc_num_layers: 2
bidirectional: True
dropout: 0.2
emb_dropout: 0.1
max_time_step: 30
report_interval: 100
eval_interval: 500
save_interval: 500
metrics: ['bleu']
shared_vocab: False
unk: True
schedule: False
schesamp: False
length_norm: True